Repository wecode-bootcamp-korea/41-1st-A.C.P-backend, pull requests merged in 2023-01, with the labels that each got.

#1 초기 환경 세팅
  .env.sample
  .gitignore
  app.js
  controllers/userController.js
  models/dbconfig.js
  models/userDao.js
  package-lock.json
  package.json
  routes/index.js
  routes/userRouter.js
  services/userService.js
Labels: 멘토 리뷰 요청

#7 [41기 김광휘] ADD: db migrations
  .DS_Store
  .gitignore
  db/migrations/20230102023729_create_users_table.sql
  db/migrations/20230104042112_create_species_table.sql
  db/migrations/20230104042125_create_sizes_table.sql
  db/migrations/20230104042138_create_moods_table.sql
  db/migrations/20230104042152_create_positions_table.sql
  db/migrations/20230104042215_create_difficulties_table.sql
  db/migrations/20230104042226_create_cares_table.sql
  db/migrations/20230104042227_create_plants_table.sql
  db/migrations/20230104042228_create_plant_images_table.sql
  db/migrations/20230104042701_create_plant_likes_table.sql
  db/migrations/20230104045907_create_nutrient_types_table.sql
  db/migrations/20230104045908_create_nutrients_table.sql
  db/migrations/20230104051033_create_pots_table.sql
  db/migrations/20230104051118_create_pot_colors_table.sql
  db/migrations/20230104051130_create_pots_pot_colors_table.sql
  db/migrations/20230104053059_create_products_table.sql
  db/migrations/20230104053426_create_carts_table.sql
  db/migrations/20230104053747_create_order_status_table.sql
  db/migrations/20230104053806_create_orders_table.sql
  db/migrations/20230104053820_create_order_products_table.sql
  db/migrations/20230104060332_create_reviews_table.sql
Labels: 수정 요청

#10 [41기 김광휘] ADD: db
  db/migrations/20230102023729_create_users_table.sql
  db/migrations/20230104042227_create_plants_table.sql
  db/migrations/20230104042228_create_plant_images_table.sql
  db/migrations/20230104042701_create_plant_likes_table.sql
  db/migrations/20230104042701_create_plants_likes_table.sql
  db/migrations/20230104045907_create_nutrient_types_table.sql
  db/migrations/20230104045908_create_nutrients_table.sql
  db/migrations/20230104051033_create_pots_table.sql
  db/migrations/20230104051118_create_pot_colors_table.sql
  db/migrations/20230104051130_create_pots_pot_colors_table.sql
  db/migrations/20230104053059_create_products_table.sql
  db/migrations/20230104053426_create_carts_table.sql
  db/migrations/20230104053747_create_order_status_table.sql
  db/migrations/20230104053806_create_orders_table.sql
  db/migrations/20230104053820_create_order_products_table.sql
  db/migrations/20230104060332_create_reviews_table.sql
Labels: 멘토 리뷰 요청

#2 ADD: signup 구현, 김광휘
  .gitignore
  app.js
  controllers/userController.js
  models/userDao.js
  routes/index.js
  routes/userRouter.js
  services/userService.js
  utils/error.js
  utils/validation-check.js
Labels: 멘토 리뷰 요청

#3 이민규 signin 구현
  .env.sample
  .gitignore
  controllers/userController.js
  models/userDao.js
  package.json
  routes/userRouter.js
  services/userService.js
  utils/auth.js
Labels: 멘토 리뷰 요청

#5 [41기 김광휘] ADD: Feature/plantdetailspage
  controllers/plantController.js
  models/.DS_Store
  models/plantDao.js
  routes/index.js
  routes/plantRouter.js
  services/plantService.js
Labels: 멘토 리뷰 요청

#16 [41기 김광휘] FIX: db - pots_table, nutrients_table
  db/migrations/20230104045908_create_nutrients_table.sql
  db/migrations/20230104051033_create_pots_table.sql
Labels: 멘토 리뷰 요청

#13 [41기 김광휘] FIX : plantDetails - plantDao, plantsController
  controllers/plantController.js
  models/plantDao.js
Labels: 멘토 리뷰 요청

#15 [41기 김광휘] ADD: getNutirentInfo 구현
  controllers/nutrientController.js
  models/nutrientDao.js
  routes/index.js
  routes/nutrientRouter.js
  services/nutrientService.js
Labels: 멘토 리뷰 요청

#22 [41기 김광휘] FIX: feature/db
  db/migrations/20230104045908_create_nutrients_table.sql
  db/migrations/20230104045909_create_nutrient_images.sql
  db/migrations/20230104051032_create_pot_sizes.sql
  db/migrations/20230104051033_create_pots_table.sql
  db/migrations/20230104051131_create_pot_images.sql
  db/migrations/20230104053426_create_carts_table.sql
  db/migrations/20230104053820_create_order_products_table.sql
Labels: 멘토 리뷰 요청

#8 [41기 이민규] add feature/pots data
  controllers/potController.js
  controllers/userController.js
  models/potDao.js
  routes/index.js
  routes/potsRouter.js
  services/potService.js
Labels: 멘토 리뷰 요청

#23 [41기 김광휘] ADD: Feature/insertorderproducts
  controllers/orderController.js
  models/orderDao.js
  models/userDao.js
  package-lock.json
  package.json
  routes/index.js
  routes/orderRouter.js
  services/orderService.js
  utils/auth.js
Labels: 멘토 리뷰 요청

#21 [41기 이민규] ADD: feature/order_list
  controllers/orderController.js
  models/orderDao.js
  routes/orderRouter.js
  services/orderService.js
  services/userService.js
Labels: 멘토 리뷰 요청

#19 [41기 김광휘] ADD: plantDataPagenation & sort API
  controllers/plantController.js
  models/plantDao.js
  routes/plantRouter.js
  services/plantService.js
Labels: 멘토 리뷰 요청

#14 [41기 이민규] ADD: feature/carts
  app.js
  controllers/cartController.js
  db/migrations/20230104051033_create_pots_table.sql
  db/migrations/20230104051130_create_pots_pot_colors_table.sql
  db/schema.sql
  models/cartsDao.js
  routes/cartsRouter.js
  routes/index.js
  services/cartsService.js
  utils/auth.js
Labels: Conflict 해결 요청, 수정 요청

#20 [41기 김광휘] ADD: filterNutrientListData
  controllers/nutrientController.js
  models/nutrientDao.js
  routes/nutrientRouter.js
  services/nutrientService.js
Labels: 멘토 리뷰 요청

#18 [41기 김광휘] ADD: plantDataFiltering
  controllers/plantController.js
  models/plantDao.js
  routes/plantRouter.js
  services/plantService.js
Labels: 멘토 리뷰 요청

#17 [41기 김광휘] ADD: filterPotListData 구현
  controllers/potController.js
  models/nutrientDao.js
  models/potDao.js
  routes/index.js
  routes/potRouter.js
  services/potService.js
Labels: 수정 요청

#9 [41기 김광휘] ADD: upsertDataToCart
  controllers/cartController.js
  db/migrations/20230104053426_create_carts_table.sql
  models/cartDao.js
  routes/cartRouter.js
  routes/index.js
  services/cartService.js
Labels: 추가 기능 구현 중
